sylius_grid:
    grids:
        brille24_admin_customer_option_group_grid:
            driver:
                name: doctrine/orm
                options:
                    class: Brille24\SyliusCustomerOptionsPlugin\Entity\CustomerOptions\CustomerOptionGroup
            fields:
                code:
                    type: string
                    label: sylius.ui.code
                name:
                    type: string
                    label: sylius.ui.name
                options:
                    type: twig
                    label: brille24.ui.customer_options
                    options:
                        template: Brille24SyliusCustomerOptionsPlugin:CustomerOptionGroup:_first_element_codes.html.twig
                products:
                    type: twig
                    label: sylius.ui.products
                    options:
                        template: Brille24SyliusCustomerOptionsPlugin:CustomerOptionGroup:_first_element_codes.html.twig

            filters:
                code:
                    type: string
                    label: sylius.ui.code
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete